"""description

Revision ID: 050b685d73d5
Revises: 
Create Date: 2026-04-13 04:53:13.978136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '050b685d73d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_reviews', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_reviews', 'priority',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_reviews', 'status',
               existing_type=postgresql.ENUM('queued', 'in_review', 'approved', 'rejected', name='review_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_reviews_assigned'), table_name='admin_reviews', postgresql_where="(status = 'in_review'::review_status)")
    op.drop_index(op.f('idx_reviews_queued'), table_name='admin_reviews', postgresql_where="(status = 'queued'::review_status)")
    op.drop_index(op.f('idx_reviews_sla'), table_name='admin_reviews', postgresql_where="(status = ANY (ARRAY['queued'::review_status, 'in_review'::review_status]))")
    op.alter_column('anti_cheat_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='cheat_severity'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'reference_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('anti_cheat_log', 'auto_action',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'resolution',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_cheat_event_type'), table_name='anti_cheat_log')
    op.drop_index(op.f('idx_cheat_severity'), table_name='anti_cheat_log', postgresql_where='(reviewed_at IS NULL)')
    op.drop_index(op.f('idx_cheat_unreviewed'), table_name='anti_cheat_log', postgresql_where='(reviewed_at IS NULL)')
    op.drop_index(op.f('idx_cheat_user'), table_name='anti_cheat_log')
    op.alter_column('coin_ledger', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('coin_ledger', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_ledger_reference'), table_name='coin_ledger', postgresql_where='(reference_id IS NOT NULL)')
    op.drop_index(op.f('idx_ledger_type'), table_name='coin_ledger')
    op.drop_index(op.f('idx_ledger_user'), table_name='coin_ledger')
    op.add_column('goal_types', sa.Column('ai_prompt', sa.Text(), nullable=True))
    op.alter_column('goal_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('goal_types', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('goal_types', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('goal_types', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'supports_location_path',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_goal_types_active'), table_name='goal_types')
    op.drop_index(op.f('idx_goal_types_slug'), table_name='goal_types')
    op.alter_column('goals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('active', 'submitted', 'approved', 'rejected', 'expired', name='goal_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goals', 'timezone_at_creation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_goals_expires_at'), table_name='goals', postgresql_where="(status = 'active'::goal_status)")
    op.drop_index(op.f('idx_goals_status'), table_name='goals', postgresql_where="(status = ANY (ARRAY['active'::goal_status, 'submitted'::goal_status]))")
    op.drop_index(op.f('idx_goals_user_date'), table_name='goals')
    op.drop_index(op.f('idx_goals_user_type'), table_name='goals')
    op.alter_column('notification_preferences', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'goal_reminder_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'reminder_minutes_before_expiry',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'notification_tone',
               existing_type=postgresql.ENUM('normal', 'friendly_banter', 'harsh', name='notification_tone'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'sweep_result_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'new_sweep_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('push_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('push_tokens', 'expo_push_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_push_tokens_user'), table_name='push_tokens', postgresql_where='(is_active = true)')
    op.alter_column('subscription_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_events', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'revenuecat_event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'revenuecat_event_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'product_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'period_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sub_events_rc_id'), table_name='subscription_events')
    op.drop_index(op.f('idx_sub_events_type'), table_name='subscription_events')
    op.drop_index(op.f('idx_sub_events_user'), table_name='subscription_events')
    op.alter_column('sweepstakes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'prize_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'rules_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sweepstakes', 'status',
               existing_type=postgresql.ENUM('upcoming', 'active', 'drawing', 'completed', 'cancelled', name='sweepstakes_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'total_entries_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'winner_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'no_purchase_necessary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'sponsor_name',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'apple_not_sponsor',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_sweepstakes_active'), table_name='sweepstakes', postgresql_where="(status = 'active'::sweepstakes_status)")
    op.drop_index(op.f('idx_sweepstakes_status'), table_name='sweepstakes')
    op.alter_column('sweepstakes_draws', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes_draws', 'algorithm_version',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sweepstakes_draws', 'random_seed',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sweepstakes_entries', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_entries_sweepstakes'), table_name='sweepstakes_entries')
    op.drop_index(op.f('idx_entries_user_sweep'), table_name='sweepstakes_entries')
    op.drop_index(op.f('idx_entries_user_total'), table_name='sweepstakes_entries')
    op.alter_column('sweepstakes_winners', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes_winners', 'prize_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sweepstakes_winners', 'claim_status',
               existing_type=postgresql.ENUM('pending', 'notified', 'claimed', 'expired', 'forfeited', name='claim_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_winners_claim_status'), table_name='sweepstakes_winners', postgresql_where="(claim_status = ANY (ARRAY['pending'::claim_status, 'notified'::claim_status]))")
    op.drop_index(op.f('idx_winners_draw'), table_name='sweepstakes_winners')
    op.drop_index(op.f('idx_winners_user'), table_name='sweepstakes_winners')
    op.alter_column('timezone_audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'old_timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'new_timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'flagged_suspicious',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'flag_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'was_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tz_audit_flagged'), table_name='timezone_audit_log', postgresql_where='(flagged_suspicious = true)')
    op.drop_index(op.f('idx_tz_audit_time'), table_name='timezone_audit_log')
    op.drop_index(op.f('idx_tz_audit_user'), table_name='timezone_audit_log')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=postgresql.ENUM('free', 'premium', name='subscription_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'revenuecat_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'coin_balance',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'ban_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_coin_balance'), table_name='users', postgresql_where='(coin_balance > 0)')
    op.drop_index(op.f('idx_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('idx_users_revenuecat_id'), table_name='users', postgresql_where='(revenuecat_customer_id IS NOT NULL)')
    op.drop_index(op.f('idx_users_subscription'), table_name='users')
    op.alter_column('verification_photos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verification_photos', 's3_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('verification_photos', 's3_bucket',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'exif_device_make',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('verification_photos', 'exif_device_model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('verification_photos', 'mime_type',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_photos_s3_key'), table_name='verification_photos')
    op.drop_index(op.f('idx_photos_user'), table_name='verification_photos')
    op.drop_index(op.f('idx_photos_verification'), table_name='verification_photos')
    op.alter_column('verifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verifications', 'status',
               existing_type=postgresql.ENUM('pending_review', 'in_review', 'approved', 'rejected', name='verification_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verifications', 'timezone_at_submission',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('verifications', 'ai_verdict',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('verifications', 'coins_awarded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_verifications_free_pending'), table_name='verifications', postgresql_where="((status = 'pending_review'::verification_status) AND (verification_path = 'free_manual'::verification_path))")
    op.drop_index(op.f('idx_verifications_goal'), table_name='verifications')
    op.drop_index(op.f('idx_verifications_status'), table_name='verifications', postgresql_where="(status = ANY (ARRAY['pending_review'::verification_status, 'in_review'::verification_status]))")
    op.drop_index(op.f('idx_verifications_submitted'), table_name='verifications')
    op.drop_index(op.f('idx_verifications_user'), table_name='verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_verifications_user'), 'verifications', ['user_id', sa.literal_column('submitted_at DESC')], unique=False)
    op.create_index(op.f('idx_verifications_submitted'), 'verifications', [sa.literal_column('submitted_at DESC')], unique=False)
    op.create_index(op.f('idx_verifications_status'), 'verifications', ['status'], unique=False, postgresql_where="(status = ANY (ARRAY['pending_review'::verification_status, 'in_review'::verification_status]))")
    op.create_index(op.f('idx_verifications_goal'), 'verifications', ['goal_id'], unique=False)
    op.create_index(op.f('idx_verifications_free_pending'), 'verifications', ['submitted_at'], unique=False, postgresql_where="((status = 'pending_review'::verification_status) AND (verification_path = 'free_manual'::verification_path))")
    op.alter_column('verifications', 'coins_awarded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('verifications', 'ai_verdict',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verifications', 'timezone_at_submission',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('verifications', 'status',
               existing_type=postgresql.ENUM('pending_review', 'in_review', 'approved', 'rejected', name='verification_status'),
               server_default=sa.text("'pending_review'::verification_status"),
               existing_nullable=False)
    op.alter_column('verifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_photos_verification'), 'verification_photos', ['verification_id'], unique=False)
    op.create_index(op.f('idx_photos_user'), 'verification_photos', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_photos_s3_key'), 'verification_photos', ['s3_key'], unique=False)
    op.alter_column('verification_photos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('verification_photos', 'mime_type',
               existing_type=sa.String(),
               server_default=sa.text("'image/jpeg'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'exif_device_model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verification_photos', 'exif_device_make',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verification_photos', 's3_bucket',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('verification_photos', 's3_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_users_subscription'), 'users', ['subscription_tier', 'subscription_expires_at'], unique=False)
    op.create_index(op.f('idx_users_revenuecat_id'), 'users', ['revenuecat_customer_id'], unique=False, postgresql_where='(revenuecat_customer_id IS NOT NULL)')
    op.create_index(op.f('idx_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_index(op.f('idx_users_coin_balance'), 'users', ['coin_balance'], unique=False, postgresql_where='(coin_balance > 0)')
    op.alter_column('users', 'ban_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'coin_balance',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'revenuecat_customer_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'subscription_tier',
               existing_type=postgresql.ENUM('free', 'premium', name='subscription_tier'),
               server_default=sa.text("'free'::subscription_tier"),
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.String(),
               server_default=sa.text("'UTC'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_tz_audit_user'), 'timezone_audit_log', ['user_id', sa.literal_column('changed_at DESC')], unique=False)
    op.create_index(op.f('idx_tz_audit_time'), 'timezone_audit_log', [sa.literal_column('changed_at DESC')], unique=False)
    op.create_index(op.f('idx_tz_audit_flagged'), 'timezone_audit_log', ['flagged_suspicious'], unique=False, postgresql_where='(flagged_suspicious = true)')
    op.alter_column('timezone_audit_log', 'was_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'flag_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'flagged_suspicious',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'new_timezone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'old_timezone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_winners_user'), 'sweepstakes_winners', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_winners_draw'), 'sweepstakes_winners', ['draw_id'], unique=False)
    op.create_index(op.f('idx_winners_claim_status'), 'sweepstakes_winners', ['claim_status'], unique=False, postgresql_where="(claim_status = ANY (ARRAY['pending'::claim_status, 'notified'::claim_status]))")
    op.alter_column('sweepstakes_winners', 'claim_status',
               existing_type=postgresql.ENUM('pending', 'notified', 'claimed', 'expired', 'forfeited', name='claim_status'),
               server_default=sa.text("'pending'::claim_status"),
               existing_nullable=False)
    op.alter_column('sweepstakes_winners', 'prize_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sweepstakes_winners', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_entries_user_total'), 'sweepstakes_entries', ['sweepstakes_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_entries_user_sweep'), 'sweepstakes_entries', ['user_id', 'sweepstakes_id'], unique=False)
    op.create_index(op.f('idx_entries_sweepstakes'), 'sweepstakes_entries', ['sweepstakes_id', 'entered_at'], unique=False)
    op.alter_column('sweepstakes_entries', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('sweepstakes_draws', 'random_seed',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sweepstakes_draws', 'algorithm_version',
               existing_type=sa.String(),
               server_default=sa.text("'crypto_random_v1'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sweepstakes_draws', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_sweepstakes_status'), 'sweepstakes', ['status', sa.literal_column('ends_at DESC')], unique=False)
    op.create_index(op.f('idx_sweepstakes_active'), 'sweepstakes', ['starts_at', 'ends_at'], unique=False, postgresql_where="(status = 'active'::sweepstakes_status)")
    op.alter_column('sweepstakes', 'apple_not_sponsor',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'sponsor_name',
               existing_type=sa.String(),
               server_default=sa.text("'MuskMaker'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'no_purchase_necessary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'winner_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'total_entries_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'status',
               existing_type=postgresql.ENUM('upcoming', 'active', 'drawing', 'completed', 'cancelled', name='sweepstakes_status'),
               server_default=sa.text("'upcoming'::sweepstakes_status"),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'rules_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sweepstakes', 'prize_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_sub_events_user'), 'subscription_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_sub_events_type'), 'subscription_events', ['revenuecat_event_type', 'processed_at'], unique=False)
    op.create_index(op.f('idx_sub_events_rc_id'), 'subscription_events', ['revenuecat_event_id'], unique=False)
    op.alter_column('subscription_events', 'period_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'product_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'revenuecat_event_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'revenuecat_event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'firebase_uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_push_tokens_user'), 'push_tokens', ['user_id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('push_tokens', 'platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'expo_push_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'new_sweep_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'sweep_result_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'notification_tone',
               existing_type=postgresql.ENUM('normal', 'friendly_banter', 'harsh', name='notification_tone'),
               server_default=sa.text("'normal'::notification_tone"),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'reminder_minutes_before_expiry',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'goal_reminder_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_goals_user_type'), 'goals', ['user_id', 'goal_type_id'], unique=False)
    op.create_index(op.f('idx_goals_user_date'), 'goals', ['user_id', sa.literal_column('local_goal_date DESC')], unique=False)
    op.create_index(op.f('idx_goals_status'), 'goals', ['status'], unique=False, postgresql_where="(status = ANY (ARRAY['active'::goal_status, 'submitted'::goal_status]))")
    op.create_index(op.f('idx_goals_expires_at'), 'goals', ['expires_at'], unique=False, postgresql_where="(status = 'active'::goal_status)")
    op.alter_column('goals', 'timezone_at_creation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('active', 'submitted', 'approved', 'rejected', 'expired', name='goal_status'),
               server_default=sa.text("'active'::goal_status"),
               existing_nullable=False)
    op.alter_column('goals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_goal_types_slug'), 'goal_types', ['slug'], unique=False)
    op.create_index(op.f('idx_goal_types_active'), 'goal_types', ['is_active', 'display_order'], unique=False)
    op.alter_column('goal_types', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('goal_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('goal_types', 'supports_location_path',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('goal_types', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty'),
               server_default=sa.text("'medium'::difficulty"),
               existing_nullable=False)
    op.alter_column('goal_types', 'icon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('goal_types', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('goal_types', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('goal_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('goal_types', 'ai_prompt')
    op.create_index(op.f('idx_ledger_user'), 'coin_ledger', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_ledger_type'), 'coin_ledger', ['transaction_type'], unique=False)
    op.create_index(op.f('idx_ledger_reference'), 'coin_ledger', ['reference_id', 'reference_type'], unique=False, postgresql_where='(reference_id IS NOT NULL)')
    op.alter_column('coin_ledger', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('coin_ledger', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_cheat_user'), 'anti_cheat_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_cheat_unreviewed'), 'anti_cheat_log', [sa.literal_column('created_at DESC')], unique=False, postgresql_where='(reviewed_at IS NULL)')
    op.create_index(op.f('idx_cheat_severity'), 'anti_cheat_log', ['severity', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(reviewed_at IS NULL)')
    op.create_index(op.f('idx_cheat_event_type'), 'anti_cheat_log', ['event_type', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('anti_cheat_log', 'resolution',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('anti_cheat_log', 'auto_action',
               existing_type=sa.String(),
               server_default=sa.text("'none'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'reference_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('anti_cheat_log', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='cheat_severity'),
               server_default=sa.text("'low'::cheat_severity"),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_reviews_sla'), 'admin_reviews', ['sla_deadline'], unique=False, postgresql_where="(status = ANY (ARRAY['queued'::review_status, 'in_review'::review_status]))")
    op.create_index(op.f('idx_reviews_queued'), 'admin_reviews', ['queued_at'], unique=False, postgresql_where="(status = 'queued'::review_status)")
    op.create_index(op.f('idx_reviews_assigned'), 'admin_reviews', ['assigned_to'], unique=False, postgresql_where="(status = 'in_review'::review_status)")
    op.alter_column('admin_reviews', 'status',
               existing_type=postgresql.ENUM('queued', 'in_review', 'approved', 'rejected', name='review_status'),
               server_default=sa.text("'queued'::review_status"),
               existing_nullable=False)
    op.alter_column('admin_reviews', 'priority',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('admin_reviews', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
