"""add has_completed_onboarding to users

Revision ID: 2d42fb4f66e1
Revises: 544733ac5c68
Create Date: 2026-04-13 23:00:19.776488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d42fb4f66e1'
down_revision: Union[str, Sequence[str], None] = '544733ac5c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'has_completed_onboarding')
    # ### end Alembic commands ###
