"""Change goaltype column. Add type

Revision ID: 47ed5e394027
Revises: 2d42fb4f66e1
Create Date: 2026-04-16 00:41:21.926790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ed5e394027'
down_revision: Union[str, Sequence[str], None] = '2d42fb4f66e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_reviews', 'priority',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('admin_reviews', 'status',
               existing_type=postgresql.ENUM('queued', 'in_review', 'approved', 'rejected', name='review_status'),
               server_default='queued',
               existing_nullable=False)
    op.create_index('idx_reviews_assigned', 'admin_reviews', ['assigned_to'], unique=False, postgresql_where=sa.text("status = 'in_review'"))
    op.create_index('idx_reviews_queued', 'admin_reviews', [sa.literal_column('queued_at ASC')], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('idx_reviews_sla', 'admin_reviews', ['sla_deadline'], unique=False, postgresql_where=sa.text("status IN ('queued', 'in_review')"))
    op.alter_column('anti_cheat_log', 'event_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='cheat_severity'),
               server_default='low',
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'reference_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('anti_cheat_log', 'auto_action',
               existing_type=sa.VARCHAR(),
               server_default='none',
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'resolution',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_cheat_event_type', 'anti_cheat_log', ['event_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_cheat_severity', 'anti_cheat_log', ['severity', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('reviewed_at IS NULL'))
    op.create_index('idx_cheat_unreviewed', 'anti_cheat_log', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('reviewed_at IS NULL'))
    op.create_index('idx_cheat_user', 'anti_cheat_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('coin_ledger', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_ledger_reference', 'coin_ledger', ['reference_id', 'reference_type'], unique=False, postgresql_where=sa.text('reference_id IS NOT NULL'))
    op.create_index('idx_ledger_type', 'coin_ledger', ['transaction_type'], unique=False)
    op.create_index('idx_ledger_user', 'coin_ledger', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.execute("CREATE TYPE goal_type AS ENUM ('photo', 'quiz')")
    op.add_column('goal_types', sa.Column('type', sa.Enum('photo', 'quiz', name='goal_type'), nullable=False))
    op.alter_column('goal_types', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('goal_types', 'slug',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('goal_types', 'icon_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('goal_types', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty'),
               server_default='medium',
               existing_nullable=False)
    op.create_index('idx_goal_types_active', 'goal_types', ['is_active', 'display_order'], unique=False)
    op.create_index('idx_goal_types_slug', 'goal_types', ['slug'], unique=False)
    op.add_column('goals', sa.Column('title', sa.Text(), nullable=False))
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('active', 'submitted', 'approved', 'rejected', 'expired', name='goal_status'),
               server_default='active',
               existing_nullable=False)
    op.alter_column('goals', 'timezone_at_creation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index('idx_goals_expires_at', 'goals', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_goals_status', 'goals', ['status'], unique=False, postgresql_where=sa.text("status IN ('active', 'submitted')"))
    op.create_index('idx_goals_user_date', 'goals', ['user_id', sa.literal_column('local_goal_date DESC')], unique=False)
    op.create_index('idx_goals_user_type', 'goals', ['user_id', 'goal_type_id'], unique=False)
    op.alter_column('notification_preferences', 'push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'goal_reminder_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'reminder_minutes_before_expiry',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'notification_tone',
               existing_type=postgresql.ENUM('normal', 'friendly_banter', 'harsh', name='notification_tone'),
               server_default='normal',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'sweep_result_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'new_sweep_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('push_tokens', 'expo_push_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'platform',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index('idx_push_tokens_user', 'push_tokens', ['user_id'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.alter_column('subscription_events', 'firebase_uid',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'revenuecat_event_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'revenuecat_event_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'product_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'period_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_sub_events_rc_id', 'subscription_events', ['revenuecat_event_id'], unique=False)
    op.create_index('idx_sub_events_type', 'subscription_events', ['revenuecat_event_type', 'processed_at'], unique=False)
    op.create_index('idx_sub_events_user', 'subscription_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('sweepstakes', 'title',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'prize_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'rules_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sweepstakes', 'status',
               existing_type=postgresql.ENUM('upcoming', 'active', 'drawing', 'completed', 'cancelled', name='sweepstakes_status'),
               server_default='upcoming',
               existing_nullable=False)
    op.alter_column('sweepstakes', 'total_entries_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'winner_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'no_purchase_necessary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'sponsor_name',
               existing_type=sa.VARCHAR(),
               server_default='MuskMaker',
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'apple_not_sponsor',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index('idx_sweepstakes_active', 'sweepstakes', ['starts_at', 'ends_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_sweepstakes_status', 'sweepstakes', ['status', sa.literal_column('ends_at DESC')], unique=False)
    op.alter_column('sweepstakes_draws', 'algorithm_version',
               existing_type=sa.VARCHAR(),
               server_default='crypto_random_v1',
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sweepstakes_draws', 'random_seed',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_entries_sweepstakes', 'sweepstakes_entries', ['sweepstakes_id', 'entered_at'], unique=False)
    op.create_index('idx_entries_user_sweep', 'sweepstakes_entries', ['user_id', 'sweepstakes_id'], unique=False)
    op.create_index('idx_entries_user_total', 'sweepstakes_entries', ['sweepstakes_id', 'user_id'], unique=False)
    op.alter_column('sweepstakes_winners', 'prize_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sweepstakes_winners', 'claim_status',
               existing_type=postgresql.ENUM('pending', 'notified', 'claimed', 'expired', 'forfeited', name='claim_status'),
               server_default='pending',
               existing_nullable=False)
    op.create_index('idx_winners_claim_status', 'sweepstakes_winners', ['claim_status'], unique=False, postgresql_where=sa.text("claim_status IN ('pending', 'notified')"))
    op.create_index('idx_winners_draw', 'sweepstakes_winners', ['draw_id'], unique=False)
    op.create_index('idx_winners_user', 'sweepstakes_winners', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('timezone_audit_log', 'old_timezone',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'new_timezone',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'flagged_suspicious',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'flag_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'was_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('idx_tz_audit_flagged', 'timezone_audit_log', ['flagged_suspicious'], unique=False, postgresql_where=sa.text('flagged_suspicious IS true'))
    op.create_index('idx_tz_audit_time', 'timezone_audit_log', [sa.literal_column('changed_at DESC')], unique=False)
    op.create_index('idx_tz_audit_user', 'timezone_audit_log', ['user_id', sa.literal_column('changed_at DESC')], unique=False)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               server_default='UTC',
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'has_completed_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=postgresql.ENUM('free', 'premium', name='subscription_tier'),
               server_default='free',
               existing_nullable=False)
    op.alter_column('users', 'revenuecat_customer_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'coin_balance',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'ban_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_users_coin_balance', 'users', ['coin_balance'], unique=False, postgresql_where=sa.text('coin_balance > 0'))
    op.create_index('idx_users_firebase_uid', 'users', ['firebase_uid'], unique=False)
    op.create_index('idx_users_revenuecat_id', 'users', ['revenuecat_customer_id'], unique=False, postgresql_where=sa.text('revenuecat_customer_id IS NOT NULL'))
    op.create_index('idx_users_subscription', 'users', ['subscription_tier', 'subscription_expires_at'], unique=False)
    op.alter_column('verification_photos', 's3_key',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('verification_photos', 's3_bucket',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'exif_device_make',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('verification_photos', 'exif_device_model',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('verification_photos', 'mime_type',
               existing_type=sa.VARCHAR(),
               server_default='image/jpeg',
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('idx_photos_s3_key', 'verification_photos', ['s3_key'], unique=False)
    op.create_index('idx_photos_user', 'verification_photos', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_photos_verification', 'verification_photos', ['verification_id'], unique=False)
    op.alter_column('verifications', 'status',
               existing_type=postgresql.ENUM('pending_review', 'in_review', 'approved', 'rejected', name='verification_status'),
               server_default='pending_review',
               existing_nullable=False)
    op.alter_column('verifications', 'timezone_at_submission',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('verifications', 'ai_verdict',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('verifications', 'coins_awarded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index('idx_verifications_free_pending', 'verifications', [sa.literal_column('submitted_at ASC')], unique=False, postgresql_where=sa.text("status = 'pending_review' AND verification_path = 'free_manual'"))
    op.create_index('idx_verifications_goal', 'verifications', ['goal_id'], unique=False)
    op.create_index('idx_verifications_status', 'verifications', ['status'], unique=False, postgresql_where=sa.text("status IN ('pending_review', 'in_review')"))
    op.create_index('idx_verifications_submitted', 'verifications', [sa.literal_column('submitted_at DESC')], unique=False)
    op.create_index('idx_verifications_user', 'verifications', ['user_id', sa.literal_column('submitted_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verifications_user', table_name='verifications')
    op.drop_index('idx_verifications_submitted', table_name='verifications')
    op.drop_index('idx_verifications_status', table_name='verifications', postgresql_where=sa.text("status IN ('pending_review', 'in_review')"))
    op.drop_index('idx_verifications_goal', table_name='verifications')
    op.drop_index('idx_verifications_free_pending', table_name='verifications', postgresql_where=sa.text("status = 'pending_review' AND verification_path = 'free_manual'"))
    op.alter_column('verifications', 'coins_awarded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verifications', 'ai_verdict',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('verifications', 'timezone_at_submission',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('verifications', 'status',
               existing_type=postgresql.ENUM('pending_review', 'in_review', 'approved', 'rejected', name='verification_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_photos_verification', table_name='verification_photos')
    op.drop_index('idx_photos_user', table_name='verification_photos')
    op.drop_index('idx_photos_s3_key', table_name='verification_photos')
    op.alter_column('verification_photos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verification_photos', 'mime_type',
               existing_type=sa.Text(),
               server_default=None,
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('verification_photos', 'exif_device_model',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('verification_photos', 'exif_device_make',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('verification_photos', 's3_bucket',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('verification_photos', 's3_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('idx_users_subscription', table_name='users')
    op.drop_index('idx_users_revenuecat_id', table_name='users', postgresql_where=sa.text('revenuecat_customer_id IS NOT NULL'))
    op.drop_index('idx_users_firebase_uid', table_name='users')
    op.drop_index('idx_users_coin_balance', table_name='users', postgresql_where=sa.text('coin_balance > 0'))
    op.alter_column('users', 'ban_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'coin_balance',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'revenuecat_customer_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'subscription_tier',
               existing_type=postgresql.ENUM('free', 'premium', name='subscription_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'has_completed_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.Text(),
               server_default=None,
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('idx_tz_audit_user', table_name='timezone_audit_log')
    op.drop_index('idx_tz_audit_time', table_name='timezone_audit_log')
    op.drop_index('idx_tz_audit_flagged', table_name='timezone_audit_log', postgresql_where=sa.text('flagged_suspicious IS true'))
    op.alter_column('timezone_audit_log', 'was_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'flag_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'flagged_suspicious',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('timezone_audit_log', 'new_timezone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('timezone_audit_log', 'old_timezone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('idx_winners_user', table_name='sweepstakes_winners')
    op.drop_index('idx_winners_draw', table_name='sweepstakes_winners')
    op.drop_index('idx_winners_claim_status', table_name='sweepstakes_winners', postgresql_where=sa.text("claim_status IN ('pending', 'notified')"))
    op.alter_column('sweepstakes_winners', 'claim_status',
               existing_type=postgresql.ENUM('pending', 'notified', 'claimed', 'expired', 'forfeited', name='claim_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes_winners', 'prize_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('idx_entries_user_total', table_name='sweepstakes_entries')
    op.drop_index('idx_entries_user_sweep', table_name='sweepstakes_entries')
    op.drop_index('idx_entries_sweepstakes', table_name='sweepstakes_entries')
    op.alter_column('sweepstakes_draws', 'random_seed',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('sweepstakes_draws', 'algorithm_version',
               existing_type=sa.Text(),
               server_default=None,
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('idx_sweepstakes_status', table_name='sweepstakes')
    op.drop_index('idx_sweepstakes_active', table_name='sweepstakes', postgresql_where=sa.text("status = 'active'"))
    op.alter_column('sweepstakes', 'apple_not_sponsor',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'sponsor_name',
               existing_type=sa.Text(),
               server_default=None,
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'no_purchase_necessary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'winner_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'total_entries_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'status',
               existing_type=postgresql.ENUM('upcoming', 'active', 'drawing', 'completed', 'cancelled', name='sweepstakes_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sweepstakes', 'rules_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('sweepstakes', 'prize_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('sweepstakes', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('idx_sub_events_user', table_name='subscription_events')
    op.drop_index('idx_sub_events_type', table_name='subscription_events')
    op.drop_index('idx_sub_events_rc_id', table_name='subscription_events')
    op.alter_column('subscription_events', 'period_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'product_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('subscription_events', 'revenuecat_event_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'revenuecat_event_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('subscription_events', 'firebase_uid',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('idx_push_tokens_user', table_name='push_tokens', postgresql_where=sa.text('is_active IS true'))
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('push_tokens', 'platform',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('push_tokens', 'expo_push_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'new_sweep_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'sweep_result_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'notification_tone',
               existing_type=postgresql.ENUM('normal', 'friendly_banter', 'harsh', name='notification_tone'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'reminder_minutes_before_expiry',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'goal_reminder_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_goals_user_type', table_name='goals')
    op.drop_index('idx_goals_user_date', table_name='goals')
    op.drop_index('idx_goals_status', table_name='goals', postgresql_where=sa.text("status IN ('active', 'submitted')"))
    op.drop_index('idx_goals_expires_at', table_name='goals', postgresql_where=sa.text("status = 'active'"))
    op.alter_column('goals', 'timezone_at_creation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('active', 'submitted', 'approved', 'rejected', 'expired', name='goal_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_column('goals', 'title')
    op.drop_index('idx_goal_types_slug', table_name='goal_types')
    op.drop_index('idx_goal_types_active', table_name='goal_types')
    op.alter_column('goal_types', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'icon_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('goal_types', 'slug',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('goal_types', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('goal_types', 'type')
    op.execute("DROP TYPE goal_type")
    op.drop_index('idx_ledger_user', table_name='coin_ledger')
    op.drop_index('idx_ledger_type', table_name='coin_ledger')
    op.drop_index('idx_ledger_reference', table_name='coin_ledger', postgresql_where=sa.text('reference_id IS NOT NULL'))
    op.alter_column('coin_ledger', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('idx_cheat_user', table_name='anti_cheat_log')
    op.drop_index('idx_cheat_unreviewed', table_name='anti_cheat_log', postgresql_where=sa.text('reviewed_at IS NULL'))
    op.drop_index('idx_cheat_severity', table_name='anti_cheat_log', postgresql_where=sa.text('reviewed_at IS NULL'))
    op.drop_index('idx_cheat_event_type', table_name='anti_cheat_log')
    op.alter_column('anti_cheat_log', 'resolution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('anti_cheat_log', 'auto_action',
               existing_type=sa.Text(),
               server_default=None,
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'reference_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('anti_cheat_log', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='cheat_severity'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anti_cheat_log', 'event_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('idx_reviews_sla', table_name='admin_reviews', postgresql_where=sa.text("status IN ('queued', 'in_review')"))
    op.drop_index('idx_reviews_queued', table_name='admin_reviews', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('idx_reviews_assigned', table_name='admin_reviews', postgresql_where=sa.text("status = 'in_review'"))
    op.alter_column('admin_reviews', 'status',
               existing_type=postgresql.ENUM('queued', 'in_review', 'approved', 'rejected', name='review_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_reviews', 'priority',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
