"""add server default for goal_types

Revision ID: 544733ac5c68
Revises: 84f27fa4fc3f
Create Date: 2026-04-13 05:11:59.334311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544733ac5c68'
down_revision: Union[str, Sequence[str], None] = '84f27fa4fc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_types', 'supports_location_path',
               existing_type=sa.BOOLEAN(),
               server_default='False',
               existing_nullable=False)
    op.alter_column('goal_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='True',
               existing_nullable=False)
    op.alter_column('goal_types', 'display_order',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_types', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_types', 'supports_location_path',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
