"""message

Revision ID: a14eaaf7a74f
Revises: d5e6f7a8b9c0
Create Date: 2026-04-21 12:55:03.012712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14eaaf7a74f'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_goal_types_slug'), table_name='goal_types')
    op.create_index('idx_goal_types_maps_query_word', 'goal_types', ['maps_query_word'], unique=False)
    op.drop_index(op.f('uq_prompt_configs_generic'), table_name='notification_prompt_configs', postgresql_where='(goal_type_id IS NULL)')
    op.drop_index(op.f('uq_prompt_configs_specific'), table_name='notification_prompt_configs', postgresql_where='(goal_type_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_prompt_configs_specific'), 'notification_prompt_configs', ['goal_type_id', 'tone', 'event_type'], unique=True, postgresql_where='(goal_type_id IS NOT NULL)')
    op.create_index(op.f('uq_prompt_configs_generic'), 'notification_prompt_configs', ['tone', 'event_type'], unique=True, postgresql_where='(goal_type_id IS NULL)')
    op.drop_index('idx_goal_types_maps_query_word', table_name='goal_types')
    op.create_index(op.f('idx_goal_types_slug'), 'goal_types', ['maps_query_word'], unique=False)
    # ### end Alembic commands ###
